# Generated by Django 4.2.7 on 2025-11-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('stopwatch', 'Chronomètre'), ('countdown', 'Minuteur')], default='stopwatch', max_length=10)),
                ('status', models.CharField(choices=[('stopped', 'Arrêté'), ('running', 'En cours'), ('paused', 'En pause')], default='stopped', max_length=10)),
                ('current_time', models.BigIntegerField(default=0)),
                ('initial_time', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
