# Generated by Django 4.2.7 on 2025-11-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du preset (ex: Sport, Travail, Pause)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description optionnelle')),
                ('duration', models.BigIntegerField(help_text='Durée en millisecondes')),
                ('color', models.CharField(default='#14a085', help_text='Couleur hex du preset', max_length=7)),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (optionnel)", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
